bringup:
  ros__parameters:
    urdf_xacro: "/home/robots/source_code/github/zenmanenergy/FRC9214/2026/code/ros_package/team9214_ws/src/arena_description/urdf/robot.urdf.xacro"
    tag_map_yaml: "/home/robots/source_code/github/zenmanenergy/FRC9214/2026/code/ros_package/team9214_ws/src/arena_tag_map/config/camera_test_arena_tags.yaml"
    observer_yaml: "/home/robots/source_code/github/zenmanenergy/FRC9214/2026/code/ros_package/team9214_ws/src/tag_pose_observer/config/observer.yaml"
    ekf_map_yaml: "/home/robots/source_code/github/zenmanenergy/FRC9214/2026/code/ros_package/team9214_ws/src/localization_fusion/config/ekf_map.yaml"
    ekf_odom_yaml: "/home/robots/source_code/github/zenmanenergy/FRC9214/2026/code/ros_package/team9214_ws/src/localization_fusion/config/ekf_odom.yaml"
    rviz_config: "/home/robots/source_code/github/zenmanenergy/FRC9214/2026/code/ros_package/team9214_ws/src/arena_bringup/config/rviz.rviz"
    apriltag_params_yaml: "/home/robots/source_code/github/zenmanenergy/FRC9214/2026/code/ros_package/team9214_ws/src/arena_tag_map/config/frc2026_apriltag_ros.yaml"
    use_rviz: true

    camera_ns: "camera_1"
    image_topic: "image_rect"
    camera_info_topic: "camera_info"
    detections_topic: "tag_detections"

    use_camera_driver: true
    use_rectify: true
    video_device: "/dev/video0"
    framerate: 15.0
    image_width: 1280
    image_height: 720
    # framerate: 30.0
    # image_width: 640
    # image_height: 480
    pixel_format: "yuyv"
    io_method: "mmap"
    camera_frame: "camera_1_optical_frame"
    # camera_info_url: "file:///home/robots/source_code/github/zenmanenergy/FRC9214/2026/code/ros_package/team9214_ws/src/multi_cam_apriltag/config/camera_1_new.yaml"
    camera_info_url: "file:///home/robots/source_code/github/zenmanenergy/FRC9214/2026/code/ros_package/team9214_ws/src/multi_cam_apriltag/config/camera_1_new.yaml"

    use_static_camera_tf: true
    # Sensor availability toggles for EKF inputs.
    # Set false when the robot is not providing those topics yet.
    use_wheel_odom: false
    use_imu: false
    # When false, only ekf_map runs and is forced to world_frame=odom.
    run_ekf_odom: false
    camera_tf_x: 0.20
    camera_tf_y: 0.00
    camera_tf_z: 0.30
    camera_tf_roll: -1.57079632679
    camera_tf_pitch: 0.0
    camera_tf_yaw: -1.57079632679
