[tool.robotpy]
# Version of robotpy this project depends on
robotpy_version = "2025.2.1.0"

# Which extra RobotPy components should be installed
robotpy_extras = []

# Robot class to use
robot_class = "robot.MyRobot"
